### PR TITLE
Fixed 'until' loop, game works

### PR DESCRIPTION
**Pull request by utahrim**
Before the "until check?" loop was going into an infinity loop, couldn't exit the game after answering incorrect. Fixed now!

### CODE REVIEW

**Comment by RebeccaKleinberg** [comment]
Good work everyone! I am going to work on adding a shuffle method later
today unless there is an objection for some reason...
Rk

**Comment by StevenXL** [comment]
@RebeccaKleinberg - no objections on my part.

I would like to work on getting the `get_card` method working on the `Deck` class. Let me know when you are done with your feature so I can start on that.

Guys - I know we were trying to get our program working so I understand why we broke  a few rules, but let's remember what a proper workflow is. Make sure you:
1. Do all your work on a new branch. Don't forget to name it with the format your-name/feature
2. Make sure you only change one file in your commit.
3. If you are working on something, let us all know so that we don't work on the same file.

**Comment by RebeccaKleinberg** [comment]
Ok, I wont be working on the shuffle method for some hours at least, so
feel free to work on the get_card method now if you like.
I will check in about it when I'm ready to start working on the shuffle
method.
£:D

**Comment by StevenXL** [comment]
@RebeccaKleinberg  Nevermind - it looks like we have that method down already. You can go ahead and work on your feature. Let us know what file you'll be working on so that we don't work on that. 

@utahrim @saraho-shea

**Comment by RebeccaKleinberg** [comment]
Ok, I am going to try to work on that tonight. I'll let you know when I get
started.
Rk
@utahrim https://github.com/utahrim @saraho-shea
https://github.com/saraho-shea

**Comment by RebeccaKleinberg** [comment]
Working on shuffle feature
@utahrim https://github.com/utahrim @saraho-shea
https://github.com/saraho-shea

**Comment by RebeccaKleinberg** [comment]
Easiest fix ever. Pull rq done.
Rk

**Pull request merged**
